# Generated by Django 4.2.7 on 2023-11-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft', models.FileField(upload_to='media/award/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/study/')),
                ('study_pic', models.ImageField(null=True, upload_to='media/images/study/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('NW', 'Новичок'), ('MD', 'Срединий'), ('AD', 'Продвинутый')], default='NW', max_length=300)),
                ('type', models.CharField(choices=[('ON', 'Onchain'), ('OF', 'Ofchain')], default='ON', max_length=300)),
                ('beginning_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало события')),
                ('description', models.TextField()),
                ('taskpic', models.ImageField(null=True, upload_to='media/images/tasks/')),
                ('website', models.URLField(max_length=250)),
                ('creator', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ED', 'Ежедневные'), ('EW', 'Еженедельные'), ('EM', 'Ежемесячные'), ('ONE', 'Один раз')], default='ED', max_length=300)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cryptogameapp.award')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['beginning_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/images/profile/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/images/profile_partner/')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Cryptogameapp.taskcard')),
            ],
        ),
    ]
