# Generated by Django 4.2.7 on 2023-11-15 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окончание события'),
        ),
    ]
