# Generated by Django 4.2.7 on 2023-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0003_alter_taskcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
