# Generated by Django 4.2.7 on 2023-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0004_alter_taskcard_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='category',
            field=models.CharField(choices=[('LK', 'Поставить лайк'), ('QR', 'Поиск соответствия')], default='LK', max_length=300),
        ),
    ]
