# Generated by Django 4.2.7 on 2023-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0005_taskcard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='progress',
            field=models.CharField(choices=[('AC', 'Аctive'), ('CM', 'Completed')], default='AC', max_length=300),
        ),
    ]
