# Generated by Django 4.2.7 on 2023-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0006_profile_twitter_username_taskcard_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_username',
            field=models.CharField(max_length=64),
        ),
    ]
