# Generated by Django 4.2.7 on 2023-11-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0007_alter_profile_twitter_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
        migrations.AddField(
            model_name='award',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='token_award',
            field=models.FileField(blank=True, null=True, upload_to='media/token_awards/'),
        ),
        migrations.AlterField(
            model_name='award',
            name='nft',
            field=models.FileField(blank=True, null=True, upload_to='media/award/'),
        ),
    ]
