# Generated by Django 4.2.7 on 2023-11-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0010_profile_binance_profile_discord_profile_phantom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
