# Generated by Django 4.2.7 on 2023-11-23 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0013_alter_taskcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='taskcard',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
