# Generated by Django 4.2.7 on 2023-11-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptogameapp', '0014_alter_partner_name_alter_studycard_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard',
            name='social_network',
            field=models.CharField(choices=[('TW', 'Twitter'), ('TG', 'Telegram'), ('DC', 'Discord')], default='TW', max_length=300),
        ),
    ]
